// Embed ../site into src/site.gen.ts, so the module bundle carries the whole site.
// Run before `spacetime publish` (npm run gen). The generated file is gitignored.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const site = join(here, '../../site');
const text = (f) => JSON.stringify(readFileSync(join(site, f), 'utf8'));
const bytes = (f) => `new Uint8Array([${[...readFileSync(join(site, f))].join(',')}])`;

writeFileSync(
  join(here, '../src/site.gen.ts'),
  `// Generated by scripts/gen-site.mjs from ../site. Do not edit.
export const INDEX_HTML = ${text('index.html')};
export const APP_JS = ${text('app.js')};
export const STYLE_CSS = ${text('style.css')};
export const LOGO_SVG = ${text('logo.svg')};
export const ICON_PNG = ${bytes('icon.png')};
`
);
console.log('wrote src/site.gen.ts');
